---
title: "Unconscious EC RRR"
subtitle: "Generate randomised trial files"
author: "Ian Hussey^[Ghent University. Email: ian.hussey@ugent.be]"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    number_sections: no
    theme: flatly
    toc: yes
    toc_float: yes
---

# to do & notes

what counterbalancing options are needed other than CS1-pos vs CS2-pos?

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)

# options
options(knitr.table.format = "html") # necessary configuration of tables

# disable scientific notation
options(scipen = 999) 

```

```{r}

# dependencies
check_for_and_install_packages <- function(package) {
  if (!package %in% installed.packages()) install.packages(package)
}

check_for_and_install_packages("tidyverse")

library(tidyverse)

```

# Generate trial sequences

```{r}

# create data for many participants
n_participants <- 150

# build vector of filler and target trials, randomise order
generate_block <- function(target_name, n_filler_trials_per_block = 52, n_target_trials_per_block = 10) {
  
  trials_filler <- paste0(rep("stimuli/filler", n_filler_trials_per_block), 
                          seq(from = 1, to = n_filler_trials_per_block, by = 1), ".jpg")
  trials_target <- paste0(rep(paste0("stimuli/", target_name), n_target_trials_per_block), 
                          seq(from = 1, to = n_target_trials_per_block, by = 1), ".jpg")
  trials_combined <- append(trials_filler, trials_target) %>% sample()
  
  # insert CS-US trials into specific locations in a master vector
  popped_trial <- c("stimuli/blank.jpg", sample(trials_CS1_US, 1), "stimuli/blank.jpg")
  trials_CS1_US_shuffled <- trials_CS1_US[trials_CS1_US != popped_trial]
  trials_combined <- append(trials_combined, popped_trial, after = 9)
  
  popped_trial <- c("stimuli/blank.jpg", sample(trials_CS2_US, 1), "stimuli/blank.jpg")
  trials_CS2_US_shuffled <- trials_CS2_US[trials_CS2_US != popped_trial]
  trials_combined <- append(trials_combined, popped_trial, after = 19)
  
  popped_trial <- c("stimuli/blank.jpg", sample(trials_CS1_US, 1), "stimuli/blank.jpg")
  trials_CS1_US_shuffled <- trials_CS1_US[trials_CS1_US != popped_trial]
  trials_combined <- append(trials_combined, popped_trial, after = 29)
  
  popped_trial <- c("stimuli/blank.jpg", sample(trials_CS2_US, 1), "stimuli/blank.jpg")
  trials_CS2_US_shuffled <- trials_CS2_US[trials_CS2_US != popped_trial]
  trials_combined <- append(trials_combined, popped_trial, after = 39)
  
  popped_trial <- c("stimuli/blank.jpg", sample(trials_CS1_US, 1), "stimuli/blank.jpg")
  trials_CS1_US_shuffled <- trials_CS1_US[trials_CS1_US != popped_trial]
  trials_combined <- append(trials_combined, popped_trial, after = 49)
  
  popped_trial <- c("stimuli/blank.jpg", sample(trials_CS2_US, 1), "stimuli/blank.jpg")
  trials_CS2_US_shuffled <- trials_CS2_US[trials_CS2_US != popped_trial]
  trials_combined <- append(trials_combined, popped_trial, after = 59)
  
  popped_trial <- c("stimuli/blank.jpg", sample(trials_CS1_US, 1), "stimuli/blank.jpg")
  trials_CS1_US_shuffled <- trials_CS1_US[trials_CS1_US != popped_trial]
  trials_combined <- append(trials_combined, popped_trial, after = 69)
  
  popped_trial <- c("stimuli/blank.jpg", sample(trials_CS2_US, 1), "stimuli/blank.jpg")
  trials_CS2_US_shuffled <- trials_CS2_US[trials_CS2_US != popped_trial]
  trials_combined <- append(trials_combined, popped_trial, after = 79)
  
  return(trials_combined)
}

```

## Condition 1: CS1_USpos

```{r}

condition <- "CS1_USpos"

# build vectors of CS US pairings
trials_CS1_US <- paste0(rep("stimuli/cs1_pos", 20), seq(from = 1, to = 20, by = 1), ".jpg")
trials_CS2_US <- paste0(rep("stimuli/cs2_neg", 20), seq(from = 1, to = 20, by = 1), ".jpg")


trials <- NULL

for(i in 1:n_participants) {
  block_a <- generate_block(target_name = "target1_")
  block_b <- generate_block(target_name = "target2_")
  block_c <- generate_block(target_name = "target3_")
  block_d <- generate_block(target_name = "target4_")
  block_e <- generate_block(target_name = "target5_")
  
  blocks_combined <- block_a %>%
    append(., block_b, after = sample(c(0, 86), 1)) %>%
    append(., block_c, after = sample(c(0, 86, 86*2), 1)) %>%
    append(., block_d, after = sample(c(0, 86, 86*2, 86*3), 1)) %>%
    append(., block_e, after = sample(c(0, 86, 86*2, 86*3, 86*4), 1))
  
  data_participant <- data.frame(stimulus = blocks_combined) %>%
    rownames_to_column(var = "trial_number") %>%
    mutate(participant = i,
           trial_number = as.numeric(as.character(trial_number))) %>% 
    select(participant, trial_number, stimulus) %>%
    mutate(trial_type = ifelse(grepl("filler", stimulus), "filler",
                               ifelse(grepl("blank", stimulus), "blank",
                                      ifelse(grepl("target", stimulus), "target",
                                             ifelse(grepl("cs", stimulus), "CSUS", NA)))),
           target_trial = ifelse(grepl("target", trial_type), TRUE, FALSE),
           correct_response = ifelse(target_trial == TRUE, "space", "None")) 
  
  write_csv(data_participant, paste0("trials_participant_", i, "_condition_", condition, ".csv")) 
}

```

## Condition 2: CS1_USneg

```{r}

condition <- "CS1_USneg"

# build vectors of CS US pairings
trials_CS1_US <- paste0(rep("stimuli/cs1_neg", 20), seq(from = 1, to = 20, by = 1), ".jpg")
trials_CS2_US <- paste0(rep("stimuli/cs2_pos", 20), seq(from = 1, to = 20, by = 1), ".jpg")


trials <- NULL

for(i in 1:n_participants) {
  block_a <- generate_block(target_name = "target1_")
  block_b <- generate_block(target_name = "target2_")
  block_c <- generate_block(target_name = "target3_")
  block_d <- generate_block(target_name = "target4_")
  block_e <- generate_block(target_name = "target5_")
  
  blocks_combined <- block_a %>%
    append(., block_b, after = sample(c(0, 86), 1)) %>%
    append(., block_c, after = sample(c(0, 86, 86*2), 1)) %>%
    append(., block_d, after = sample(c(0, 86, 86*2, 86*3), 1)) %>%
    append(., block_e, after = sample(c(0, 86, 86*2, 86*3, 86*4), 1))
  
  data_participant <- data.frame(stimulus = blocks_combined) %>%
    rownames_to_column(var = "trial_number") %>%
    mutate(participant = i,
           trial_number = as.numeric(as.character(trial_number))) %>% 
    select(participant, trial_number, stimulus) %>%
    mutate(trial_type = ifelse(grepl("filler", stimulus), "filler",
                               ifelse(grepl("blank", stimulus), "blank",
                                      ifelse(grepl("target", stimulus), "target",
                                             ifelse(grepl("cs", stimulus), "CSUS", NA)))),
           target_trial = ifelse(grepl("target", trial_type), TRUE, FALSE),
           correct_response = ifelse(target_trial == TRUE, "space", "None"))
  
  write_csv(data_participant, paste0("trials_participant_", i, "_condition_", condition, ".csv")) 
}

```

