---
title: "Unconscious EC RRR"
subtitle: "Process data"
author: "Ian Hussey^[Ghent University. Email: ian.hussey@ugent.be]"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    number_sections: no
    theme: flatly
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE)

# options
options(knitr.table.format = "html") # necessary configuration of tables

# disable scientific notation
options(scipen = 999) 

```

```{r}

# dependencies
check_for_and_install_packages <- function(package) {
  if (!package %in% installed.packages()) install.packages(package)
}

check_for_and_install_packages("tidyverse")
check_for_and_install_packages("plyr")
check_for_and_install_packages("data.table")

library(tidyverse)

```

# Get data

```{r}

# load these packages only for this chunk, then unload them, as they interfere with tidyverse packages
library(plyr)
library(data.table)

# list all folders in a given folder. ie all data collection sites' separate data folders
the_directories <- 
  #list.dirs(path = "raw - pilot", full.names = TRUE, recursive = FALSE) %>%
  list.dirs(path = "raw - pilot", full.names = TRUE, recursive = FALSE) %>%
  paste0(., "/")

fread_with_name_checks <- function(input){
  fread(input = input, check.names = TRUE, header = TRUE)
}

# function to get all files with the extension ".csv" in a given folder, and read them into a single data frame
all_csv_files_to_data_frame <- function(the_path){
  require(tidyverse)
  require(plyr)
  require(data.table)
  
  data_output <- 
    list.files(path = the_path, pattern = "\\.csv$") %>%
    paste0(the_directories[i], .) %>%
    lapply(fread_with_name_checks) %>%
    rbind.fill() %>%
    as.tibble()
  
  return(data_output)
}

# pull data from each site into a single list
## declare empty list
data_raw_list <- list()

## loop over directories and files in them
for(i in seq_along(the_directories)){
  data_from_given_site <- all_csv_files_to_data_frame(the_path = the_directories[i])
  data_from_given_site$site <- i
  data_raw_list[[i]] <- data_from_given_site
}

## flatten list
data_raw <- dplyr::bind_rows(data_raw_list)

detach("package:plyr", unload=TRUE)
detach("package:data.table", unload=TRUE)

```

# Process data

tidy names and levels

```{r}

data_trimmed <- data_raw %>%
  dplyr::rename(filler_1_rating = filler_1_rating.response,
                filler_2_rating = filler_2_rating.response,
                surveillance_response_correct = surveillance_response.corr,
                evaluation_CS1_preferred = evaluation_response.corr,
                awareness_1_question = awareness_1_trials_loop.thisTrialN,
                awareness_1_response = awareness_1_response.keys,
                awareness_2a_question = awareness_2a_trials_loop.thisTrialN,
                awareness_2a_response = awareness_type_2a_rating.response,
                awareness_2b_question = awareness_2b_trials_loop.thisTrialN,
                awareness_2b_response = awareness_type_2b_rating.response,
                awareness_2c_question = awareness_2c_trials_loop.thisTrialN,
                awareness_2c_response = awareness_type_2c_rating.response) %>%
  dplyr::mutate(simulated_data = ifelse(UseMonkey == "y", TRUE, FALSE),
                unique_id = paste(data_collection_site, participant, sep = "_")) %>%
  dplyr::select(unique_id, age, gender,
                data_collection_site,
                condition,
                simulated_data,
                # surveillance task
                surveillance_response_correct,
                # filler task
                filler_1_rating,
                filler_2_rating,
                # evaluation task
                evaluation_response_indicating_CS1_preferred,
                evaluation_CS1_preferred,
                left_stimulus,
                right_stimulus,
                awareness_1_question,
                awareness_1_response,
                awareness_2a_question,
                awareness_2a_response,
                awareness_2b_question,
                awareness_2b_response,
                awareness_2c_question,
                awareness_2c_response) %>%
  # filter out simulated data
  filter(simulated_data == FALSE)

# process data from each task
data_demographics <- data_trimmed %>%
  distinct(unique_id, .keep_all = TRUE) %>%
  select(unique_id, age, gender, data_collection_site, condition, simulated_data)

data_surveillance <- data_trimmed %>%
  filter(!is.na(surveillance_response_correct)) %>%
  group_by(unique_id) %>%
  summarize(surveillance_response_total_correct_responses = sum(surveillance_response_correct)) %>%
  ungroup()

data_filler_1 <- data_trimmed %>%
  filter(!is.na(filler_1_rating)) %>%
  group_by(unique_id) %>%
  summarize(sum_score_filler_1 = sum(filler_1_rating)) %>%
  ungroup()

data_filler_2 <- data_trimmed %>%
  filter(!is.na(filler_2_rating)) %>%
  group_by(unique_id) %>%
  summarize(sum_score_filler_2 = sum(filler_2_rating)) %>%
  ungroup()

data_evaluation <- data_trimmed %>%
  filter(!is.na(evaluation_CS1_preferred) & 
           evaluation_response_indicating_CS1_preferred != "None") %>%
  # original study codes preference for CSpos as +1 and preference for CSneg as -1, so we do the same here. 
  mutate(evaluation_CS1_preferred = ifelse(evaluation_CS1_preferred == 1, 1, 
                                           ifelse(evaluation_CS1_preferred == 0, -1, NA))) %>%
  # convert CS1/2 to CSpos/neg
  mutate(evaluation_CSpos_preferred = ifelse(condition == "CS1_USpos", evaluation_CS1_preferred,
                                             ifelse(condition == "CS1_USneg", evaluation_CS1_preferred*-1, NA))) %>%
  group_by(unique_id) %>%
  summarize(sum_score_evaluation_CSpos_preferred = sum(evaluation_CSpos_preferred)) %>%
  ungroup()

```

make strings human readable

```{r}

# function to convert the keypresses captured in psychopy to a human readable string
psychopy_text_to_string <- function(vector_input){
  
  # remove shift key responses
  vector_input <- vector_input %>%
    unlist() %>%
    str_replace_all(., "lshift", "") %>%
    str_replace_all(., "rshift", "")
  
  # apply participants' backspaces 
  while ( !is.na(match("backspace", vector_input)) ) {
    location_backspace      <- match("backspace", vector_input)
    location_previous       <- location_backspace - 1
    locations_to_be_deleted <- append(location_backspace, location_previous)
    vector_input            <- vector_input[-locations_to_be_deleted]
  }
  
  # convert puntuation to characters and collapse string
  vector_input <- vector_input %>%
    str_replace_all(., "return",       "")  %>%
    str_replace_all(., "period",       ".") %>%
    str_replace_all(., "comma",        ",") %>%
    str_replace_all(., "space",        " ") %>%
    str_replace_all(., "question",     "?") %>%
    str_replace_all(., "doublequote",  "'") %>%
    str_replace_all(., "apostrophe",   "'") %>%
    str_replace_all(., "semicolon",    ";") %>%
    str_replace_all(., "num_decimal",  ".") %>%
    str_replace_all(., "num_subtract", "-") %>%
    str_replace_all(., "capslock",     "") %>%
    paste(., collapse = "")
  
  return(vector_input)
}

data_awareness_1 <- data_trimmed %>%
  mutate(awareness_1_response = ifelse(awareness_1_response == "", NA, awareness_1_response)) %>%
  filter(!is.na(awareness_1_response)) %>%
  mutate(awareness_1_response = str_remove_all(awareness_1_response, "\\["),
         awareness_1_response = str_remove_all(awareness_1_response, "\\]"),
         awareness_1_response = str_remove_all(awareness_1_response, "'"),
         awareness_1_response = str_split(awareness_1_response, pattern = ", ")) %>%
  rowwise() %>%
  mutate(awareness_1_response = psychopy_text_to_string(awareness_1_response)) %>%
  ungroup() %>%
  select(unique_id, awareness_1_question, awareness_1_response) %>%
  mutate(awareness_1_question = recode(awareness_1_question, 
                                       "0" = "awareness_1_out_of_ordinary",
                                       "1" = "awareness_1_systematic",
                                       "2" = "awareness_1_words_and_images")) %>%
  spread(awareness_1_question, awareness_1_response)

```

recode other awareness variables and create exclusion variables

```{r}

data_awareness_2a <- data_trimmed %>%
  filter(!is.na(awareness_2a_response)) %>%
  select(unique_id, awareness_2a_question, awareness_2a_response) %>%
  mutate(awareness_2a_question = recode(awareness_2a_question, 
                                       "0" = "awareness_2_regularity"),
         awareness_2a_response = as.numeric(awareness_2a_response)) %>%
  mutate(awareness_2a_response = recode(awareness_2a_response, 
                                         "1" = FALSE,
                                         "2" = TRUE)) %>%
  select(-awareness_2a_question)

data_awareness_2b <- data_trimmed %>%
  filter(!is.na(awareness_2b_response)) %>%
  select(unique_id, awareness_2b_question, awareness_2b_response) %>%
  mutate(awareness_2b_question = recode(awareness_2b_question, 
                                       "0" = "awareness_2_stim_paired_with_positive",
                                       "1" = "awareness_2_stim_paired_with_negative"),
         awareness_2b_response = as.numeric(awareness_2b_response)) %>%
  spread(awareness_2b_question, awareness_2b_response)
# needs condition var to know if correct

data_awareness_2c <- data_trimmed %>%
  filter(!is.na(awareness_2c_response)) %>%
  select(unique_id, awareness_2c_question, awareness_2c_response) %>%
  mutate(awareness_2c_question = recode(awareness_2c_question, 
                                       "0" = "familiarity"),
         awareness_2c_response = as.numeric(awareness_2c_response)) %>%
  spread(awareness_2c_question, awareness_2c_response)

# combine 
data_combined <- data_demographics %>%
  left_join(data_surveillance,  by = "unique_id") %>%
  left_join(data_filler_1,      by = "unique_id") %>%
  left_join(data_filler_2,      by = "unique_id") %>%
  left_join(data_evaluation,    by = "unique_id") %>%
  left_join(data_awareness_1,   by = "unique_id") %>%
  left_join(data_awareness_2a,  by = "unique_id") %>%
  left_join(data_awareness_2b,  by = "unique_id") %>%
  left_join(data_awareness_2c,  by = "unique_id")

# exclusions
## accuracy in the surveillance task
## "Performance in the surveillance task: we will exclude participants with more than three standard deviations beyond the mean error number in the surveillance task (error = responding to non-target trials, or not responding to target trials)."
data_exclusions_temp_1 <- data_combined %>%
  group_by(data_collection_site) %>%
  summarize(mean_surveillance_response_total_correct_responses_by_site = round(mean(surveillance_response_total_correct_responses), 2),
            sd_surveillance_response_total_correct_responses_by_site = round(sd(surveillance_response_total_correct_responses), 2)) %>%
  ungroup()

data_exclusions_temp_2 <- data_combined %>%
  left_join(data_exclusions_temp_1, by = "data_collection_site") %>%
  mutate(exclude_surveillance = ifelse(surveillance_response_total_correct_responses <
                                         (mean_surveillance_response_total_correct_responses_by_site - 
                                            sd_surveillance_response_total_correct_responses_by_site*3) |
                                         surveillance_response_total_correct_responses >
                                         (mean_surveillance_response_total_correct_responses_by_site + 
                                            sd_surveillance_response_total_correct_responses_by_site*3), TRUE, FALSE))

# awareness of the stimulus pairings
data_intermediate <- data_exclusions_temp_2 %>%
  # Confirmatory 1: applied later after hand scoring of responses
  # Exporatory 1: applied later after hand scoring of responses
  # Exploratory 2: bar anan, de houwer and nosek criteria
  # "The second (exploratory) score will be computed based on Bar-Anan et al.’s (2010) criteria. Here participants will be excluded if they chose the “yes” answer on question 1 of the Bar-Anan et al. measure, and retained if they chose “no”."
  mutate(exclude_awareness_baranan_dehouwer_nosek = awareness_2a_response) %>%
  # Exploratory 3: bar anan, de houwer and nosek criteria
  # "The third (exploratory) score will be computed based on a modification to Bar-Anan et al.’s (2010) criteria in order to verify that responding is not driven by guessing. Participants will be excluded if they chose the “yes” answer on question 1 and correctly identify the valence with which each of the two CSs appeared during the task (providing either a probably or certainly response on questions 2-3). All other participants will be retained." 
  mutate(exclude_awareness_baranan_dehouwer_nosek_modified = ifelse((exclude_awareness_baranan_dehouwer_nosek == TRUE & 
                                                                       condition == "CS1_USpos" & 
                                                                       awareness_2_stim_paired_with_positive %in% c(1, 2) & 
                                                                       awareness_2_stim_paired_with_negative %in% c(5, 6)) |
                                                                      (exclude_awareness_baranan_dehouwer_nosek == TRUE &
                                                                         condition == "CS1_USneg" & 
                                                                         awareness_2_stim_paired_with_positive %in% c(5, 6) & 
                                                                         awareness_2_stim_paired_with_negative %in% c(1, 2)), 
                                                                    TRUE, FALSE))

# add columns for hand scoring
data_awareness_for_hand_scoring <- data_intermediate %>%
  select(unique_id, 
         condition, 
         awareness_1_out_of_ordinary, 
         awareness_1_systematic) %>%
  mutate(fazio_and_olsen_criteria_scorer_1 = "",
         fazio_and_olsen_modified_criteria_scorer_1 = "",
         fazio_and_olsen_criteria_scorer_2 = "",
         fazio_and_olsen_modified_criteria_scorer_2 = "")

# write to disk
## combined data without variables to be hand scored
write_csv(data_intermediate, "intermediate/data_intermediate.csv")

## data for hand scoring
write_csv(data_awareness_for_hand_scoring, "intermediate/data_awareness_for_hand_scoring.csv")

```




